import type { Metadata } from 'next'
import { Nunito_Sans } from 'next/font/google'
import { Poppins } from 'next/font/google'
import './globals.css'

import Header from "./components/AppShell/Header.js"
import Nav from "./components/AppShell/Nav.js"

const nunito_sans = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito_sans',
})

const poppins = Poppins({
  weight: ['500', '600', '700'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito_sans.variable} ${poppins.variable} font-body bg-gradient-to-br from-[#141D34] to-navy text-white min-h-screen`}>
        
        <Header />

        <div className='flex flex-col md:flex-row'>

          <div className="w-full md:w-[18.75%] md:max-w-screen-2xs border-t md:border-t-0 md:border-r border-white border-opacity-10 fixed z-10 bottom-0 md:top-[69px] md:h-[calc(100vh_-_69px)] md:pt-12 lg:pt-16 md:px-6 bg-navy md:bg-transparent before:absolute before:top-0 before:w-full before:bg-gradient-to-r before:from-purple before:to-pink before:h-px md:before:bg-none">
            <div className='w-full md:max-w-44 ml-auto'>
              <Nav />
            </div>
          </div>

          <main className='w-full md:w-[81.25%] md:left-[18.75%] relative lg:pl-20 pt-24 lg:pt-20 pb-24 md:pb-0 px-6 md:p-16 md:top-[69px]'>
            <div className="">
              {children}
            </div>
          </main>

        </div>
        
      </body>
    </html>
  )
}
